version: "3"

services:
  
  postgres:
      image: postgres
      environment:
          POSTGRES_PASSWORD: inco
      volumes:
          - ./postgres/pgdata:/var/lib/postgresql/data
      ports:
          - 5432:5432

  api:
    build: ./server
    container_name: api
    restart: always
    expose:
        - 8000
    depends_on:
        - postgres


  ui:
      build: ./ui
      container_name: ui
      restart: always
      ports:
          - "80:80"
      depends_on:
          - api
      volumes:
          - .:/app

